name: Run Script as Cron Job

on:
  # See [Events that trigger workflows | GitHub Docs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule).
  schedule:
    - cron: "*/15 7-19 * * *" # Every 15 minutes, from 8AM to 20AM UTC+1

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: Run
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run script
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: node index.js
